author           = Bob64
depends          = hopper
description      = Adds hopper compatibility for other mods like technic and elepower.
name             = hopper_compat
optional_depends = elepower_machines, technic_chests, connected_chests, pipeworks, airtanks, bees, claycrafter
title            = IA Hopper Compatibility
